// Regenerates src/brand/glyphPaths.js from ../brand/glyphs/*.svg so the
// SVG files remain the single source of truth for linework.
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const glyphDir = join(here, '..', '..', 'brand', 'glyphs')
const outFile = join(here, '..', 'src', 'brand', 'glyphPaths.js')

const glyphs = {}
for (const file of readdirSync(glyphDir).filter((f) => f.endsWith('.svg'))) {
  const raw = readFileSync(join(glyphDir, file), 'utf8')
  const inner = raw.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '')
  const viewBox = (raw.match(/viewBox="([^"]+)"/) || [])[1] || '0 0 100 120'
  glyphs[file.replace('.svg', '')] = { viewBox, inner }
}

mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(
  outFile,
  '// AUTO-GENERATED by scripts/sync-glyphs.mjs — do not edit. Edit brand/glyphs/*.svg instead.\n' +
  'export const GLYPHS = ' + JSON.stringify(glyphs, null, 2) + '\n'
)
console.log('glyphPaths.js written with', Object.keys(glyphs).length, 'glyphs')
